version: "3.9"
services:

  spring-api-image:
    image: spring-api-image
    container_name: spring-api-prueba-tecnica
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerDB
      MYSQL_USER:  Leonispe
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  spring-network:
volumes:
  mysql-volume: